const particlesConfig = {
    name: "tsparticles-preset-links",
    version: "2.5.3",
    description: "tsParticles links preset",
    homepage: "https://particles.js.org",
    repository: {
      type: "git",
      url: "git+https://github.com/matteobruni/tsparticles.git",
      directory: "presets/links"
    },
    keywords: [
      "front-end",
      "frontend",
      "tsparticles",
      "particles.js",
      "particlesjs",
      "particles",
      "particle",
      "canvas",
      "jsparticles",
      "xparticles",
      "particles-js",
      "particles-bg",
      "particles-bg-vue",
      "particles-ts",
      "particles.ts",
      "react-particles-js",
      "react-particles.js",
      "react-particles",
      "react",
      "reactjs",
      "vue-particles",
      "ngx-particles",
      "angular-particles",
      "particleground",
      "vue",
      "vuejs",
      "preact",
      "preactjs",
      "jquery",
      "angularjs",
      "angular",
      "typescript",
      "javascript",
      "animation",
      "web",
      "html5",
      "web-design",
      "webdesign",
      "css",
      "html",
      "css3",
      "animated",
      "background",
      "confetti",
      "canvas",
      "fireworks",
      "fireworks-js",
      "confetti-js",
      "confettijs",
      "fireworksjs",
      "canvas-confetti",
      "tsparticles-preset"
    ],

  }
export default particlesConfig